baseurl = "https://nicokosi.github.io/"
title = "Nicokosi's blog"
enableRobotsTXT = true
enableEmoji = true

theme = "beautifulhugo"

disqusShortname = "nicokosi-blog"
googleAnalytics = "UA-11930016-2"

[author]
name = "Nicolas Kosinski"

[params]
logo = "images/nicokosi.png"
mainSections = ["post","posts"]

[params.highlight]
style = "github"
languages = ["java", "scala", "clojure", "haskell", "shell"]

DefaultContentLanguage = "en"
copyright = "&copy; <a href=\"https://github.com/nicokosi\">Nicolas Kosinski</a>"

[languages]
  [languages.en]
    title = "Nicokosi's blog"
    weight = 1
    [languages.en.params]
  [languages.fr]
    title = "Le blog de Nicokosi"
    weight = 2
    [languages.fr.params]
      [languages.fr.params.navigation]
        help = "Aide"