theme = "linkita"

title = "nicokosi's blog"
description = "About software development, with topics like: exploring programming langages, experimenting with data visualisation, productivity improvements etc."
author = "nicokosi"


# The URL the site will be built for
base_url = "https://nicokosi.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

default_language = "en"

generate_feeds = true

[[taxonomies]]
name = "tags"
authors = ["nicokosi"]

[languages.fr]
title = "Le blog de nicokosi"
description = "A propos de développement logiciel : explorations diverses, découverte de langages de programmation, personnalisation de l'environnement de développement etc."
generate_feeds = true
taxonomies = [{ name = "tags", authors = ["nicokosi"] }]

[extra]
# comment = true
# math = true
# mermaid = true
# page_info = []
header_menu_name = "main"
disable_javascript = false

[extra.cover]
# image = ""
# alt = ""

[extra.menus]
main = [{ url = "$BASE_URL/tags/", name = "Tags", names_i18n = "common_tags" }]
main_fr = [{ url = "$BASE_URL/tags/", name = "Tags" }]

[extra.profiles]

# Your profile
[extra.profiles.nicoskosi]
avatar_url = "icons/github.svg"
avatar_invert = true
# avatar_alt = "Default alt text"
# name = "Default name"
# bio = "Default bio"
social = [
    { name = "github", url = "https://github.com/nicokosi" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]
[extra.profiles.nicokosi.languages]
[extra.profiles.nicokosi.languages.en]
name = "Nicokosi's blog"
bio = "a developer"
avatar_alt = "?"

[extra.profiles.nicokosi.languages.fr]
name = "Le blog de nicokosi"
bio = "un développeur"

# My profile
[extra.profiles.nicokosi]
name = "Nicolas Kosinski"
social = [
    { name = "github", url = "https://github.com/nicoksi" },
    { name = "bluesky", url = "https://bsky.app/profile/nicokosi.bsky.social" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]
