baseurl = "https://nicokosi.github.io/"
title = "Nicokosi's blog"
enableRobotsTXT = true
enableEmoji = true

DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = false

theme = "beautifulhugo"

copyright = "&copy; <a href=\"https://github.com/nicokosi\">Nicolas Kosinski</a> 2016"
disqusShortname = "nicokosi-blog"
googleAnalytics = "UA-11930016-2"

[author]
name = "nicokosi"

[params.logo]
url="/images/nicokosi.jpg"

[params.highlight]
style = "github"
languages = ["java", "scala", "clojure", "haskell", "shell"]

[Languages]
[Languages.fr]
weight = 1
title = "Le blog de Nicokosi"
languageName = "fr"

[[languages.fr.menu.main]]
url    = "/fr"
name   = "fr"
weight = 0

[Languages.en]
weight = 2
title = "Nicokosi's blog"
languageName = "en"

[[languages.en.menu.main]]
url    = "/en"
name   = "en"
weight = 0


defaultContentLanguage = "fr"
[languages.en]
  languageCode = "en"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "This is Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"
