name: Linting
on: pull_request

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1
      with:
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini
        files: __onlyModified

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}